# 텐서 조작하기 

In [7]:
import torch
import numpy as np

In [8]:
x = [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

In [9]:
x = np.array(x)

In [10]:
x.shape

(4, 3, 3)

In [11]:
x = torch.tensor(x)

In [12]:
type(x)

torch.Tensor

In [13]:
x.dim()

3

In [16]:
print(x[:,1])

tensor([[0.3000, 0.5000, 0.1000],
        [0.3000, 0.5000, 0.2000],
        [0.3000, 0.5000, 0.1000],
        [0.3000, 0.5000, 0.2000]], dtype=torch.float64)


In [17]:
print(x[:,2])

tensor([[0.7000, 0.6000, 0.5000],
        [0.7000, 0.6000, 0.5000],
        [0.5000, 0.6000, 0.7000],
        [0.5000, 0.6000, 0.7000]], dtype=torch.float64)


In [18]:
print(x[:,:-1])

tensor([[[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.1000]],

        [[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.2000]],

        [[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.1000]],

        [[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.2000]]], dtype=torch.float64)


# 브로드 캐스팅

In [19]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])
